### ISSUE TITLE
It keeps randomly opening with error

### ISSUE THREAD

**Issue by acorcutt** [Booligoosh/makerlog-menubar#6]
I keep seeing this, not when entering a task just opens randomly when doing other things - could be because of bad network connection but need to click the icon to hide every time...

<img width="1280" alt="Screenshot 2019-06-16 at 11 33 05" src="https://user-images.githubusercontent.com/198915/59563120-91780200-902d-11e9-94c4-ac4b05c1445c.png">

**Comment by Booligoosh** [comment]
Hey, sorry about this! Should be fixed now, let me know if you keep running into the issue.
