### ISSUE TITLE
Error on first run after install

### ISSUE THREAD

**Issue by pablobb** [Booligoosh/makerlog-menubar#7]
Error from screenshot occurred after the first run.
The process is listed but the app itself is not accessible
![image](https://user-images.githubusercontent.com/217570/60420721-ae453580-9be8-11e9-95c9-fa3ee982dd08.png)
![image](https://user-images.githubusercontent.com/217570/60420975-2a3f7d80-9be9-11e9-8fe6-25f8c746d1cb.png)

**Comment by pablobb** [comment]
I've cloned the repo, an error occurs because the app is trying to load not existing file: _Icon.ico_ instead of _IconOld.ico_

**Comment by Booligoosh** [comment]
Hey @pablobb, thanks for reporting. That was a silly mistake by me. Should be fixed now, hope you enjoy! 😅
